name = "decode-do"
route = { pattern = "*decode.do/*", zone_name = "decode.do" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-09-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
